name: PyPI Release

on:
  pull_request:
    types:
      - closed
    paths:
      - 'pyproject.toml'
    branches: 
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Check changelog
        run: |
          VERSION=$(poetry version | awk '{print $2}')
          if ! grep -q "Version $VERSION" CHANGES.rst; then
            echo "No changelog entry found for version $VERSION"
            exit 1
          fi

      - name: Build and publish
        run: |
          poetry install --no-dev
          poetry build
          poetry config pypi-token.pypi ${{ secrets.WORDVIEW_PYPI_TOKEN }}
          poetry publish
